Allow the OSC IP, OSC Port and Script to be configured
yewnyx/SubLink pull request #10
Opened 2024-01-07 15:18 UTC by LauraRozier

Allows the OSC IP address, OSC Port and script name to be configured in settings.json

2024-01-22 18:46 UTC, yewnyx requested changes

2024-01-22 18:46 UTC, yewnyx commented on SubLinkCommon/SubLinkService.cs
> +        _settings = _settingsMonitor.CurrentValue;
If introducing mutability is required then it should ideally be constrained as much as possible, or explained clearly what the expected scope of the mutability should be and what behavior is desired/what is not desired.

If you feel strongly about this then please add a comment in the code justifying it.

2024-01-22 18:46 UTC, yewnyx commented on SubLink/Program.cs
> +    "ScriptName": "SubLink.cs"
If they have non-null/non-empty defaults I feel like they shouldn't be in the default settings file, but documented instead.

Also, I feel like the OSC settings are not inherently SubLink settings but I might be splitting hairs a bit too much.

2024-03-02 03:52 UTC, LauraRozier commented
Closing because this can be implemented via the new modular system branch

2024-03-02 03:52 UTC, closed without merging